spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database: h2
